curl:
	curl -X GET \
	-H 'Content-Type:application/json' \
	https://pypi.org/stats/

curl2:
	curl -X GET \
	-H 'Content-Type:application/json' \
	https://hugovk.github.io/top-pypi-packages/top-pypi-packages-365-days.json
