version: '3'

services:
    pisort-api:
        build: ./main
        restart: always
        tty: true
        ports:
            - 8080:8080
        networks:
            - nginx
    
networks: 
    nginx:
        external: true
