version: '3'

services:
    pisort-api:
        build: ./main
        tty: true
        ports:
            - 8080:3000
        networks:
            - nginx
    
networks: 
    nginx:
        external: true
