curl/get:
	curl -X GET -vv 0.0.0.0:8080

curl/get/wrong:
	curl -X GET -vvv 0.0.0.0:8080/image

curl/post:
	curl -POST \
	-H 'Content-Type:application/json' \
	-d '{"message":"import numpy as np\nimport math\nimport a\nimport z\nimport az\nimport pandas"}' \
	0.0.0.0:8080

