curl:
	curl -X GET -v 127.0.0.1:8080

curl/post:
	curl \
	-XPOST \
	-H 'Content-Type:application/json' \
	-d '{"message":"import numpy as np\nimport sys, os"}' \
	-v \
	127.0.0.1:8080

test:
	python3 test_app.py

